// <auto-generated />
using Labb1_LINQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1_LINQ.Migrations
{
    [DbContext(typeof(LinqLabbDBContext))]
    [Migration("20240411141653_DB name change")]
    partial class DBnamechange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb1_LINQ.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseName = "Programmering",
                            TeacherID = 1
                        },
                        new
                        {
                            CourseID = 2,
                            CourseName = "Språk",
                            TeacherID = 2
                        },
                        new
                        {
                            CourseID = 3,
                            CourseName = "Matematik",
                            TeacherID = 3
                        });
                });

            modelBuilder.Entity("Labb1_LINQ.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            StudentName = "Fredrik"
                        },
                        new
                        {
                            StudentID = 2,
                            StudentName = "Johan"
                        },
                        new
                        {
                            StudentID = 3,
                            StudentName = "Sara"
                        },
                        new
                        {
                            StudentID = 4,
                            StudentName = "Peter"
                        },
                        new
                        {
                            StudentID = 5,
                            StudentName = "Susan"
                        },
                        new
                        {
                            StudentID = 6,
                            StudentName = "Annie"
                        },
                        new
                        {
                            StudentID = 7,
                            StudentName = "Henrik"
                        },
                        new
                        {
                            StudentID = 8,
                            StudentName = "Stina"
                        },
                        new
                        {
                            StudentID = 9,
                            StudentName = "Petronella"
                        },
                        new
                        {
                            StudentID = 10,
                            StudentName = "Leon"
                        });
                });

            modelBuilder.Entity("Labb1_LINQ.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.HasKey("StudentID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            CourseID = 1
                        },
                        new
                        {
                            StudentID = 2,
                            CourseID = 1
                        },
                        new
                        {
                            StudentID = 3,
                            CourseID = 1
                        },
                        new
                        {
                            StudentID = 4,
                            CourseID = 2
                        },
                        new
                        {
                            StudentID = 5,
                            CourseID = 2
                        },
                        new
                        {
                            StudentID = 6,
                            CourseID = 3
                        },
                        new
                        {
                            StudentID = 7,
                            CourseID = 3
                        },
                        new
                        {
                            StudentID = 8,
                            CourseID = 3
                        },
                        new
                        {
                            StudentID = 9,
                            CourseID = 1
                        },
                        new
                        {
                            StudentID = 10,
                            CourseID = 1
                        });
                });

            modelBuilder.Entity("Labb1_LINQ.Models.Subject", b =>
                {
                    b.Property<int>("SubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubID"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubID = 1,
                            SubjectName = "Programmering 1"
                        },
                        new
                        {
                            SubID = 2,
                            SubjectName = "Programmering 2"
                        },
                        new
                        {
                            SubID = 3,
                            SubjectName = "Avancerad .NET"
                        },
                        new
                        {
                            SubID = 4,
                            SubjectName = "Svenska"
                        },
                        new
                        {
                            SubID = 5,
                            SubjectName = "Engelska"
                        },
                        new
                        {
                            SubID = 6,
                            SubjectName = "Geometri"
                        },
                        new
                        {
                            SubID = 7,
                            SubjectName = "Algebra"
                        });
                });

            modelBuilder.Entity("Labb1_LINQ.Models.SubjectCourse", b =>
                {
                    b.Property<int>("SubID")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.HasKey("SubID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("SubjectCourses");

                    b.HasData(
                        new
                        {
                            SubID = 1,
                            CourseID = 1
                        },
                        new
                        {
                            SubID = 2,
                            CourseID = 1
                        },
                        new
                        {
                            SubID = 3,
                            CourseID = 1
                        },
                        new
                        {
                            SubID = 4,
                            CourseID = 2
                        },
                        new
                        {
                            SubID = 5,
                            CourseID = 2
                        },
                        new
                        {
                            SubID = 6,
                            CourseID = 3
                        },
                        new
                        {
                            SubID = 7,
                            CourseID = 3
                        });
                });

            modelBuilder.Entity("Labb1_LINQ.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            TeacherName = "Anas"
                        },
                        new
                        {
                            TeacherID = 2,
                            TeacherName = "Reidar"
                        },
                        new
                        {
                            TeacherID = 3,
                            TeacherName = "Tobias"
                        });
                });

            modelBuilder.Entity("Labb1_LINQ.Models.Course", b =>
                {
                    b.HasOne("Labb1_LINQ.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Labb1_LINQ.Models.StudentCourse", b =>
                {
                    b.HasOne("Labb1_LINQ.Models.Course", "Courses")
                        .WithMany("Students")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1_LINQ.Models.Student", "Students")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Labb1_LINQ.Models.SubjectCourse", b =>
                {
                    b.HasOne("Labb1_LINQ.Models.Course", "Courses")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb1_LINQ.Models.Subject", "Subjects")
                        .WithMany("SubjectCourses")
                        .HasForeignKey("SubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Labb1_LINQ.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Labb1_LINQ.Models.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Labb1_LINQ.Models.Subject", b =>
                {
                    b.Navigation("SubjectCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
